import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { elconsole, callAPI } from "@/helpers/helpers";

// const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps() {
	const res = await fetch("https://es.wikipedia.org/w/api.php?action=query&prop=extracts&exlimit=1&titles=pizza&explaintext=1&exsectionformat=plain&format=json&lang=es");
	const data = await res.json();

	const testdefinicion = data.query.pages[Object.keys(data.query.pages)].extract;

	return {
		props: {
			todos: data,
			testdefinicion,
		},
	};
}

export default function Home({ todos, testdefinicion }) {
	const [palabra, setpalabra] = useState();
	const [definicion, setdefinicion] = useState();

	useEffect(() => {
	}, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<section id={styles.buscador}>
				<h1 className={styles.palabraBuscada}>
					{ palabra && <span className={styles.arrowright} /> }
					<span>{palabra}</span>
				</h1>
				<div className={styles.contenedor}>
					<input
						className={styles.inputbuscar}
						type="text"
						onChange={(evt) => {
							setpalabra(evt.target.value);
							callAPI(evt.target.value);
							const signi = callAPI(evt.target.value);
							const ela = { muero: signi };
							setdefinicion(ela);
							/*
							*/
						}}
					/>
					<button className={styles.botonBuscar} type="button" onClick={elconsole(palabra)}>BUSCAR</button>
				</div>
				<p className={styles.definicion}>{ definicion ? `si ${console.debug(definicion.muero)}` : "no" }</p>
			</section>
		</>
	);
}
